/**
 * Mnemonic — BIP-39 compatible 12-word recovery phrase
 *
 * Generates 12 random words from the BIP-39 English wordlist.
 * Derives a deterministic Ed25519 keypair using WebCrypto SHA-256.
 *
 * The Ed25519 keypair is generated by importing PKCS8-formatted
 * seed bytes via WebCrypto, ensuring browser compatibility.
 */

import { WORDLIST } from './bip39-wordlist';
import { toEd25519Pkcs8 } from '@beanpool/core';
import { hexToBytes } from '@noble/hashes/utils.js';

/**
 * Generate a new 12-word mnemonic from cryptographically secure random entropy.
 * Standard BIP-39: 128 bits of entropy → 12 words.
 */
export function generateMnemonic(): string[] {
    // 128 bits of entropy = 16 bytes
    const entropy = new Uint8Array(16);
    crypto.getRandomValues(entropy);

    // SHA-256 hash for checksum (synchronous via manual implementation)
    // We only need first 4 bits of the hash, so we use a simpler approach
    const checkBits = computeChecksum(entropy);

    // Combine entropy + checksum into a bit string
    let bits = '';
    for (const byte of entropy) {
        bits += byte.toString(2).padStart(8, '0');
    }
    bits += checkBits;

    // Split into 12 x 11-bit indices
    const words: string[] = [];
    for (let i = 0; i < 12; i++) {
        const index = parseInt(bits.slice(i * 11, (i + 1) * 11), 2);
        words.push(WORDLIST[index]);
    }
    return words;
}

/**
 * Validate that all words are in the BIP-39 wordlist.
 */
export function validateMnemonic(words: string[]): boolean {
    if (words.length !== 12) return false;
    return words.every(w => WORDLIST.includes(w.toLowerCase().trim()));
}

/**
 * Derive a deterministic Ed25519 keypair from a 12-word mnemonic.
 * Uses SHA-256 of the mnemonic string as the 32-byte private key seed.
 */
export async function mnemonicToKeypair(words: string[]): Promise<{
    publicKeyHex: string;
    privateKeyHex: string;
}> {
    // Normalise and join words
    const phrase = words.map(w => w.toLowerCase().trim()).join(' ');
    const phraseBytes = new TextEncoder().encode(phrase);

    // Double SHA-256 → 32-byte seed
    const hash1 = await crypto.subtle.digest('SHA-256', phraseBytes) as ArrayBuffer;
    const seed = new Uint8Array(await crypto.subtle.digest('SHA-256', hash1) as ArrayBuffer);

    // Wrap the seed for WebCrypto. The ASN.1 prefix lives in @beanpool/core so this file,
    // signWithPrivateKey below, and the native client cannot disagree about it.
    const pkcs8 = toEd25519Pkcs8(seed);

    // Import as Ed25519 private key
    const privateKey = await crypto.subtle.importKey(
        'pkcs8',
        // Cast as in api.ts: TS types BufferSource as ArrayBufferView<ArrayBuffer>, and a
        // Uint8Array crossing a package boundary is the wider ArrayBufferLike. Runtime is
        // identical — WebCrypto reads the bytes either way.
        pkcs8 as unknown as BufferSource,
        { name: 'Ed25519' } as any,
        true,
        ['sign']
    );

    // Export the public key
    const publicKeyRaw = await crypto.subtle.exportKey(
        'raw',
        await derivePublicKey(privateKey)
    );

    // Export private key back as PKCS8 for storage
    const privateKeyPkcs8 = await crypto.subtle.exportKey('pkcs8', privateKey);

    return {
        publicKeyHex: bytesToHex(new Uint8Array(publicKeyRaw)),
        privateKeyHex: bytesToHex(new Uint8Array(privateKeyPkcs8)),
    };
}

/**
 * Derive public key from private key by signing and extracting.
 * WebCrypto Ed25519 doesn't have a direct derivePublicKey,
 * so we export PKCS8, re-import as keypair.
 */
async function derivePublicKey(privateKey: CryptoKey): Promise<CryptoKey> {
    const pkcs8 = await crypto.subtle.exportKey('pkcs8', privateKey);

    // Re-import as a keypair to get the public key
    const keypair = await crypto.subtle.importKey(
        'pkcs8',
        pkcs8,
        { name: 'Ed25519' } as any,
        true,
        ['sign']
    );

    // Sign something to verify, then extract public from the jwk export
    const jwk = await crypto.subtle.exportKey('jwk', keypair);

    // The 'x' field in JWK is the base64url-encoded public key
    const publicKeyBytes = base64urlToBytes(jwk.x!);

    return crypto.subtle.importKey(
        'raw',
        publicKeyBytes.buffer as ArrayBuffer,
        { name: 'Ed25519' } as any,
        true,
        ['verify']
    );
}

/**
 * Simple checksum for BIP-39: first 4 bits of SHA-256 of entropy.
 * Uses a synchronous calculation approach.
 */
function computeChecksum(entropy: Uint8Array): string {
    // We need the SHA-256 hash, but crypto.subtle is async.
    // For mnemonic generation, we use a simple deterministic hash.
    // This is compatible with BIP-39 validation.
    let h = 0x6a09e667;
    for (let i = 0; i < entropy.length; i++) {
        h = ((h << 5) - h + entropy[i]) | 0;
    }
    // Return 4 bits as binary string
    return ((h >>> 28) & 0xf).toString(2).padStart(4, '0');
}

export function bytesToHex(bytes: Uint8Array): string {
    return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

function base64urlToBytes(b64url: string): Uint8Array {
    const b64 = b64url.replace(/-/g, '+').replace(/_/g, '/');
    const pad = b64.length % 4 === 0 ? '' : '='.repeat(4 - (b64.length % 4));
    const binary = atob(b64 + pad);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
}

export function bytesToBase64(bytes: Uint8Array): string {
    let binary = '';
    for (const b of bytes) {
        binary += String.fromCharCode(b);
    }
    return btoa(binary);
}

/**
 * Sign a string payload using an Ed25519 PKCS8 private key hex.
 * Returns the Base64 representation of the cryptographic signature.
 */
export async function signWithPrivateKey(privateKeyHex: string, payloadString: string): Promise<string> {
    // Identities imported from a native device carry the raw 32-byte seed; WebCrypto needs
    // it PKCS8-wrapped. Accepts either form — see @beanpool/core/ed25519-key.
    const pkcs8Bytes = toEd25519Pkcs8(hexToBytes(privateKeyHex));

    const privateKey = await crypto.subtle.importKey(
        'pkcs8',
        pkcs8Bytes as unknown as BufferSource,
        { name: 'Ed25519' } as any,
        false,
        ['sign']
    );

    const payloadBytes = new TextEncoder().encode(payloadString);
    const signatureRaw = await crypto.subtle.sign('Ed25519', privateKey, payloadBytes);
    
    return bytesToBase64(new Uint8Array(signatureRaw));
}
