# BeanPool Deployment Targets Configuration
# Format: ID:NAME:HOST_OR_IP:DNS_RECORD:SSH_USER:TARGET_DIRECTORY
4:review:ssh-vic.beanpool.org:review.beanpool.org:root:BeanPool-Review
7:melb:ssh-vic.beanpool.org:melb.beanpool.org:root:BeanPool-Melb
8:castlemaine:ssh-vic.beanpool.org:castlemaine.beanpool.org:root:BeanPool-Castlemaine
9:bris:ssh-qld.beanpool.org:bris.beanpool.org:root:BeanPool-Bris
10:mullum:ssh-qld.beanpool.org:mullum.beanpool.org:root:BeanPool-Mullum
11:test:ssh-qld.beanpool.org:test.beanpool.org:root:BeanPool-Test
