import { deflateSync } from 'zlib';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

const sourcePath = join(root, 'scripts/daily-pulse-source.json');
const targetPath = join(root, 'apps/server/src/daily-pulse-entries.ts');

const entries = JSON.parse(readFileSync(sourcePath, 'utf8'));
if (!Array.isArray(entries) || entries.length === 0) {
    throw new Error(`Expected non-empty array in ${sourcePath}, got ${typeof entries}`);
}

const compressed = deflateSync(JSON.stringify(entries), { level: 9 }).toString('base64');

const tsContent = `// AUTO-GENERATED by scripts/compress-pulse.mjs — edit scripts/daily-pulse-source.json instead
import { inflateSync } from 'zlib';

export interface DailyPulseEntry {
    id: number;
    headline: string;
    body: string;
    category: string;
}

const COMPRESSED_PULSE_BASE64 = "${compressed}";

let _cachedEntries: DailyPulseEntry[] | null = null;

/**
 * Returns the full list of 300 Daily Pulse entries, lazily decompressed and cached.
 */
export function getAllPulseEntries(): DailyPulseEntry[] {
    if (!_cachedEntries) {
        const raw = inflateSync(Buffer.from(COMPRESSED_PULSE_BASE64, 'base64'));
        _cachedEntries = JSON.parse(raw.toString('utf8')) as DailyPulseEntry[];
    }
    return _cachedEntries;
}

/**
 * Returns the Daily Pulse entry for a given day index (modulo 300).
 */
export function getPulseEntry(dayIndex: number): DailyPulseEntry {
    const list = getAllPulseEntries();
    const safeIndex = ((Math.floor(dayIndex) % list.length) + list.length) % list.length;
    return list[safeIndex];
}

/**
 * Returns today's Daily Pulse entry based on local calendar day (advances in sync with 5:00 AM local rotation).
 */
export function getTodaysPulseEntry(now: Date = new Date()): DailyPulseEntry {
    const localEpochMs = now.getTime() - (now.getTimezoneOffset() * 60 * 1000);
    const dayIndex = Math.floor(localEpochMs / 86400000);
    return getPulseEntry(dayIndex);
}
`;

writeFileSync(targetPath, tsContent, 'utf8');
console.log(`✅ Successfully compiled ${entries.length} Daily Pulse entries into ${targetPath} (${Buffer.from(compressed, 'base64').length} bytes compressed)`);
